### PR TITLE
Upgrade PHP to 7.4.12

### PR DESCRIPTION
**Pull request by badrange**
Active Support for PHP 7.3 ends on December 6 2020 and I think now is a good time to start upgrading the infrastructure to the most recent major version of PHP. 

I don't know enough about your infrastructure to know if it is safe to upgrade just like this, or if we should create a separate branch or our own 7.4-based Dockerfile?

### CODE REVIEW

**Comment by badrange** [comment]
I'm now working on a Symfony based project so I could live without Drush support too :-)

**Comment by Jancis** [comment]
There's an upcoming change that allows overriding base image for builder container -
1. Allow injecting builder base image while still overlaying our custom applications: https://github.com/wunderio/silta-circleci/compare/feature/override_base
2. Use custom executor and supply (circleci) base image: https://github.com/wunderio/drupal-project-k8s/compare/feature/override_builder
So I believe it would also fix this issue too.

**Comment by badrange** [comment]
Excellent news! Is there a way to test this upcoming change already or should I just be patient?

**Comment by badrange** [comment]
So we should just close this PR then?

**Comment by Jancis** [comment]
I merged PR I mentioned above and tried the code snippet, but it feels like CircleCI does not allow defining build-args for the executor. I asked them support on this, will post an update.
If anything, we'll make and support multiple concurrent versions of circleci builder, but a sudden change won't happen (proposed in this PR) as it might potentially break other builds.

**Comment by badrange** [comment]
Thank you for the update! Since we know that we will not merge this PR I created an issue to follow up this: #126 

Feel free to edit the issue to match what you are planning to do - my perspective is so much of an outsider that I'm not sure if the issue makes sense the way I described it :-)

**Pull request closed without merging**
